name: Visual Tests

# all pull requests
on: pull_request

jobs:
  visual-tests:
    name: SauceLabs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Install latest npm
        # magi-cli 1.0 requires npm 7 or higher
        run: "npm install -g npm@8"

      - name: Install project npm dependencies
        run: "npm ci"

      - name: Run visual tests on SauceLabs
        run: "npm run test:visual"
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
